#!/bin/bash

export AWS_ACCESS_KEY_ID={INSERT_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY={INSERT_SECRET_ACCESS_KEY}
export AWS_SESSION_TOKEN={INSERT_SESSION_TOKEN}

aws ec2 terminate-instances \
    --instance-ids {INSERT_INSTANCE_ID}
